### ISSUE TITLE
Edge Case of Connection String Becomes an Invalid URL According to urlparse

### ISSUE THREAD

**Issue by dallinb** [cbdq-io/sbus-router#28]
A connection string can potentially give us a URL of `amqps://RootManageSharedAccessKey:A+A+/aa=@localhost:5671` which is valid for Azure Service Bus, but goes wrong when urlparse tries to parse it:

```
>>> from urllib.parse import urlparse
>>> url = 'amqps://RootManageSharedAccessKey:A+A+/aa=@localhost:5671'
>>> o = urlparse(url)
>>> o.scheme
'amqps'
>>> o.netloc
'RootManageSharedAccessKey:A+A+'
>>> o.port
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ben.dalling/.pyenv/versions/3.12.1/lib/python3.12/urllib/parse.py", line 182, in port
    raise ValueError(f"Port could not be cast to integer value as {port!r}")
ValueError: Port could not be cast to integer value as 'A+A+'
```

**Comment by dallinb** [comment]
Probably need to ditch attempting to convert to an AMQP URL and ensure we connect using the barest details.  We'd then provide the proton connect with a url of only "{scheme}://hostname:{port}" and provide the user name and password in the kwargs.
